#!/bin/bash
# Ручное копирование файлов из Downloads

echo "📋 Manual file copy helper"
echo ""
echo "If you downloaded files from Colab, they should be in ~/Downloads"
echo ""
echo "Please run these commands manually:"
echo ""
echo "  # 1. Check if files are in Downloads:"
echo "  ls -lh ~/Downloads/*Qwen*0.5B*"
echo ""
echo "  # 2. If found, copy them:"
echo "  cp ~/Downloads/mmlu__Qwen__Qwen2.5-0.5B-Instruct__K4__qlast.* \\"
echo "     /Users/aeshef/Downloads/sinks/hypotheses/H0_sanity/data/"
echo ""
echo "  # 3. Verify:"
echo "  ls -lh /Users/aeshef/Downloads/sinks/hypotheses/H0_sanity/data/*.jsonl.gz"
echo "  python -c \"import gzip; f=gzip.open('hypotheses/H0_sanity/data/mmlu__Qwen__Qwen2.5-0.5B-Instruct__K4__qlast.jsonl.gz','rt'); print('Lines:', len([l for l in f if l.strip()]))\""
echo ""
echo "---"
echo ""
echo "Or if VS Code synced files directly, check:"
echo "  - File Explorer in VS Code"
echo "  - Look for files in hypotheses/H0_sanity/data/"
echo "  - Right-click → Download/Save if needed"
echo ""
